scenarios/urls.py
from django.conf.urls import url

from . import views
app_name = 'scenarios'
urlpatterns = [
    url(r'^$', views.ScenariosList.as_view(), name='index'),
    url(r'author/add/$', views.ScenarioCreate.as_view(), name='add'),
    url(r'^(?P<pk>[0-9]+)/$', views.ScenariosDetail.as_view(), name='detail'),
]

solrates_demo/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from . import views

urlpatterns = [
    # Examples:
    # url(r'^$', 'solrates_demo.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),

    url(r'^$', views.index, name='index' ),
    url(r'^scenarios/', include('scenarios.urls')),
    url(r'^admin/', include(admin.site.urls)),
]

scenarios/models.py
from __future__ import unicode_literals

from django.db import models
from django.utils.encoding import python_2_unicode_compatible
from django.core.urlresolvers import reverse

import math

# Create your models here.

@python_2_unicode_compatible  # only if you need to support Python 2
class Assumptions(models.Model):
    installers_start = models.IntegerField(default=1)
    installers_weekly_growth = models.FloatField(default=0.10)
    deal_frequency_in_weeks = models.IntegerField(default=8)
    deal_latency_in_weeks = models.IntegerField(default=4)
    deal_revenue_thousands = models.IntegerField(default=5)
    target_monthly_revenue = models.IntegerField(default=20)

    def __str__(self):
        return "%.0f%% growth of $%i K @ %i weeks + %i latency until $%i K/month" % (
            self.installers_weekly_growth * 100,
            self.deal_revenue_thousands,
            self.deal_frequency_in_weeks,
            self.deal_latency_in_weeks,
            self.target_monthly_revenue
        )
    def get_absolute_url(self):
        return reverse('scenarios:detail', kwargs={'pk': self.pk})
    
    def target_monthly_deals(self):
        return self.target_monthly_revenue * 1.0 / self.deal_revenue_thousands
        
    def target_weekly_deals(self):
        return self.target_monthly_deals() / 4.4

    def target_installers(self):
        return self.target_weekly_deals() * self.deal_frequency_in_weeks
    
    def linear_weeks_to_target(self):
        weeks = (self.target_installers() - self.installers_start) / self.installers_weekly_growth
        int_weeks = math.ceil(weeks)
        return "%.0f (%.0f)" % (int_weeks, int_weeks + self.deal_latency_in_weeks)

    def exponential_weeks_to_target(self):
        growth = self.target_installers() / self.installers_start
        weeks = math.log(growth) / math.log(1 + self.installers_weekly_growth)
        int_weeks = math.ceil(weeks)
        return "%.0f (%.0f)" % (int_weeks, int_weeks + self.deal_latency_in_weeks)
    
class Weekly(models.Model):
    assumptions = models.ForeignKey(Assumptions, on_delete=models.CASCADE)
    week_index = models.IntegerField(default=1)
    installers_current = models.FloatField(default=0.0)
    installers_count = models.IntegerField(default=0)
    deals_count = models.IntegerField(default=0)
    deals_revenue = models.IntegerField(default=0)
    deals_revenue_cumulative = models.IntegerField(default=0)

    def __str__(self):
        return "%i: %i/%i ($K) for %i installers " % (
            self.week_index,
            self.deals_revenue,
            self.deals_revenue_cumulative,
            self.installers_count,
        )

    

scenarios/views.py
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponse
from models import Assumptions
from django.views import generic

class ScenariosList(generic.ListView):
    model = Assumptions

class ScenariosDetail(generic.DetailView):
    model = Assumptions

class ScenarioCreate(generic.CreateView):
    model = Assumptions
    fields = [
        'installers_start',
        'installers_weekly_growth',
        'deal_frequency_in_weeks',
        'deal_latency_in_weeks',
        'deal_revenue_thousands',
        'target_monthly_revenue',
    ]

solrates_demo/views.py
from django.http import HttpResponse


def index(request):
    return HttpResponse("<h1>Greetings</h1>Welcome to Dr. Ernie's SolRates demo app.<p> Check <a href='/scenarios/'>here</a> to explore growth scenarios.")

scenarios/templates/scenarios/assumptions_detail.html
<h1>Scenario Detail</h1>
{{ object }}

<dl>
    <dt>Target Revenue per Month</dt>
    <dd>{{ object.target_monthly_revenue }}</dd>
    <dt>Target # of Deals per Month</dt>
    <dd>{{ object.target_monthly_deals }}</dd>
    <dt>Target # of Deals per Week</dt>
    <dd>{{ object.target_weekly_deals }}</dd>
    <dt>Target # of Installers</dt>
    <dd>{{ object.target_installers }}</dd>
    <dt>Weeks to Target (Linear Growth)</dt>
    <dd>{{ object.linear_weeks_to_target }}</dd>
    <dt>Weeks to Target (Exponential Growth)</dt>
    <dd>{{ object.exponential_weeks_to_target }}</dd>
</dl>
<p>
<a href="{% url 'scenarios:index' %}">Return to List</a>
</p>

scenarios/templates/scenarios/assumptions_form.html
<h1>Create Scenario</h1>
<form action="" method="post">{% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Create" />
</form>

scenarios/templates/scenarios/assumptions_list.html
{% if object_list %}
    <ul>
    {% for scenario in object_list %}
        <li><a href="{% url 'scenarios:detail' scenario.id %}">{{ scenario }}</a></li>
    {% endfor %}
    </ul>
{% else %}
    <p>No scenarios are available.</p>
{% endif %}
<p><a href="{% url 'scenarios:add' %}">Create new scenario</a></p>